### ISSUE TITLE
Check if user exists during multi invite

### ISSUE THREAD

**Issue by SaicharanKandukuri** [GDSCParulUniversity/GitHub-multi-user-invite#2]
it is better to check if a user exists before sending an invite

> Multiple users introduce some issues,

**Comment by suraniharsh** [comment]
I would like to work on this issue. Can you provide more details or guidance?

**Comment by SaicharanKandukuri** [comment]
GitHub requests are written in [utils.py](https://github.com/GDSCParulUniversity/GitHub-multi-user-invite/blob/main/utils.py)

Refer to this [page]( https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#list-organization-members) for  to get current members in the org
